{
 "title": "Cycled distance",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Highscore",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  username,\n  max(session_meters) AS \"session_meters\"\nFROM bike_sessions\nWHERE\n  $__timeFilter(finished_at)\nGROUP BY username\nORDER BY max(session_meters)"
    }
   ]
  },
  {
   "title": "Total Distance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  finished_at AS \"time\",\n  username AS metric,\n  sum(session_meters) over (partition by username order by finished_at rows between unbounded preceding and current row)\nFROM bike_sessions\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Session Distance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(finished_at,$__interval),\n  username AS metric,\n  sum(session_meters) AS \"session_meters\"\nFROM bike_sessions\nWHERE\n  $__timeFilter(finished_at)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}