apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt
  name: {{ include "biketracker.fullname" . }}
spec:
  tls:
  - secretName: {{ include "biketracker.fullname" . }}-cert-gateway-secret
    hosts:
    - biketracker.ingress.kubernetes.etimo.se
  rules:
  - host: biketracker.ingress.kubernetes.etimo.se
    http:
      paths:
      - backend:
          serviceName: {{ include "biketracker.fullname" . }}
          servicePort: http
        path: /
