apiVersion: v1
kind: Service
metadata:
  name: {{ include "biketracker.fullname" . }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "biketracker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
