[package]
name = "biketracker-shared"
version = "0.1.0"
authors = ["Teo Klestrup Röijezon <teo@nullable.se>"]
edition = "2018"

[dependencies]
serde = "1.0.87"
serde_derive = "1.0.87"

[dependencies.uuid]
version = "0.7.2"
features = ["v4", "serde"]